name: Setup node.js

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: npm
        cache-dependency-path: package-lock.json
    - run: npm ci
      shell: bash
