version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "packages/*"
    exclude-paths:
      - "docs/**"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 14
    schedule: # TODO
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "nix"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "build"
  - package-ecosystem: "gradle"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*paperweight*"
      - dependency-name: "*purpur-api*"
      - dependency-name: "gradle-wrapper"
      - dependency-name: "*spotless*"
