import { type RegistryId } from './plugin-registry.ts'

export const local: RegistryId[] = [
  'essentialsx',
  'fastasyncworldedit',
  'luckperms',
  'plugmanx',
  'protocollib',
  'vault',
  'nuvotifier',
  'vertex'
]

export const development: RegistryId[] = local.concat(
  'bkcommonlib',
  'coreprotect',
  'decentholograms',
  'essentialsxchat',
  'essentialsxspawn',
  'fastasyncvoxelsniper',
  'multiversecore',
  'multiverseprotals',
  'placeholderapi',
  'tab',
  'terra',
  'veinminer',
  'viaversion',
  'worldguard',
  'venturechat',
  'particlehats',
  'protocollib',
  'advancedban',
  'signshop',
  'mypet',
  'minepacks',
  'slotmachine',
  'mycommand',
  'simpleelevator',
  'inventoryshop',
  'crackshotguns',
  'joincommands',
  'tntruneloaded',
  'gsit',
  'lwc',
  'skript',
  'zvoteparty',
  'floodgate',
  'geyser',
  'openinv',
  'lunachat',
  'worldeditsui',
  'worldborder',
  'imageonmap',
  'chestcommands',
  'arceon',
  'ezedits',
  'oyasaivehicles',
  'tokenmanager',
  'dynamicprofile',
  'oyasaiadmintools',
  'oyasaiutilities',
  'painttools',
  'sociallikes3',
  'tpswitch',
  'vertex',
  'pvparena'
)

export const production: RegistryId[] = development.concat('discordsrv', 'bluemap')
