// metrics.js
// /sldata で候補にする統計指標の定義集。
// classic script なのでトップレベルの var / function はグローバル。
"use strict";

var WEEK_LABELS = [
  "6/8",
  "6/15",
  "6/22",
  "6/29",
  "7/6",
  "7/13",
  "7/20",
  "7/27",
  "8/3",
];
var MONTH_LABELS = [
  "1月",
  "2月",
  "3月",
  "4月",
  "5月",
  "6月",
  "7月",
  "8月",
  "9月",
];

var SRC = {
  outbound:
    "BuildLikes を playerUuid=自分で絞り、Builds.ownerUuid / likedAt で集計",
  inbound:
    "Builds.ownerUuid=自分の建築に付いた BuildLikes を liker / likedAt で集計",
  mutual:
    "BuildLikes と Builds を自己結合し、自分が押した相手と自分に押した相手を比較",
  graph: "BuildLikes の liker-owner グラフから集計",
  time: "BuildLikes.likedAt を期間で GROUP BY。likedAt NULL の過去分は時系列から落ちる",
  buildsTime: "Builds.createdAt と BuildLikes.likedAt を期間で GROUP BY",
  space: "Builds.worldName / locX/Y/Z / chunkX/Z と BuildLikes を GROUP BY",
  rank: "Builds と BuildLikes を buildId で GROUP BY してランキング化",
  publicity:
    "PublicityHistoryRows.timestamp / slId と BuildLikes.likedAt を前後比較",
  attr: "Builds.title / comment / discordTextId / checked と BuildLikes を GROUP BY",
  achievement: "Builds と BuildLikes の累計・期間集計から進捗率を算出",
  missingLogin: "ログイン時刻・プレイ時間・参加日が現在のスキーマに無い",
  missingVisit: "プレイヤーの移動履歴・訪問済みエリアが現在のスキーマに無い",
  subjective: "統計値は作れるが、診断ロジックや重み付けは別途定義が必要",
};

function zid(n) {
  return (n < 10 ? "00" : n < 100 ? "0" : "") + n;
}
function shortName(s) {
  var out = "",
    count = 0;
  for (var ch of s.replace(/\([^)]*\)/g, "")) {
    if (count >= 9) break;
    out += ch;
    count++;
  }
  return out;
}
function sampleFor(no, chart, n, fixed) {
  var out = [],
    cap = fixed ? 100 : 0;
  for (var i = 0; i < n; i++) {
    var v = ((no * 17 + i * 11 + (i % 3) * 7) % 53) + 4;
    if (chart === "line")
      v = Math.max(
        1,
        Math.round((i ? out[i - 1] : v) + (i % 2 ? 7 : -4) + (no % 5)),
      );
    if (chart === "area")
      v = Math.max(1, Math.round(8 + i * (3 + (no % 4)) + (no % 7)));
    if (fixed)
      v = Math.min(
        cap,
        Math.round(28 + i * (52 / Math.max(1, n - 1)) + (no % 13) - 6),
      );
    out.push(v);
  }
  if (chart === "hbar")
    out.sort(function (a, b) {
      return b - a;
    });
  return out;
}
function makeMetric(d) {
  var n = d.n || (d.chart === "hbar" ? 6 : 9);
  var fixed = d.max != null;
  var labels =
    d.labels === "week"
      ? WEEK_LABELS.slice(0, n)
      : d.labels === "month"
        ? MONTH_LABELS.slice(0, n)
        : null;
  var title = d.title || shortName(d.name) + " {v}";
  return {
    id: "m" + zid(d.no),
    no: d.no,
    category: d.category,
    name: d.name,
    chart: d.chart,
    n: n,
    axis: fixed ? { mode: "fixed", max: d.max } : { mode: "nice" },
    unit: d.unit || "件",
    title: title,
    sub: d.sub === undefined ? "前回比 {d}" : d.sub,
    xLabels: labels,
    hover: d.hover || "{label} / " + (d.unit || "件") + " {v}",
    sample: d.sample || sampleFor(d.no, d.chart, n, fixed),
    source: d.source,
    feasible: d.feasible,
  };
}

var C1 = "対人・交流系",
  C2 = "時系列・トレンド系",
  C3 = "空間・ワールド系",
  C4 = "ランキング・比較・分布系",
  C5 = "掲載(publicity_history)系",
  C6 = "属性相関系",
  C7 = "ゲーミフィケーション・実績系",
  C8 = "ネタ・遊び心系",
  C9 = "自己分析・診断・レポート系";

var METRIC_SPECS = [
  {
    no: 1,
    category: C1,
    name: "今週自分がいいねした人",
    chart: "bar",
    unit: "人",
    labels: "week",
    source: SRC.outbound,
    feasible: "yes",
  },
  {
    no: 2,
    category: C1,
    name: "誰によく自分にいいねをつけてくれるか",
    chart: "hbar",
    unit: "いいね",
    source: SRC.inbound,
    feasible: "yes",
  },
  {
    no: 3,
    category: C1,
    name: "相互いいねペア",
    chart: "hbar",
    unit: "ペア",
    source: SRC.mutual,
    feasible: "yes",
  },
  {
    no: 4,
    category: C1,
    name: "応援している作者の幅(DISTINCT owner)",
    chart: "bar",
    unit: "人",
    labels: "week",
    source: SRC.outbound,
    feasible: "yes",
  },
  {
    no: 5,
    category: C1,
    name: "応援されている層の幅(ユニークいいね人数)",
    chart: "bar",
    unit: "人",
    labels: "week",
    source: SRC.inbound,
    feasible: "yes",
  },
  {
    no: 6,
    category: C1,
    name: "いいね返礼率",
    chart: "bar",
    unit: "%",
    max: 100,
    labels: "week",
    source: SRC.mutual,
    feasible: "yes",
  },
  {
    no: 7,
    category: C1,
    name: "お気に入りビルダーの捕捉率(コンプリート度)",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.outbound,
    feasible: "yes",
  },
  {
    no: 8,
    category: C1,
    name: "初対面いいね(初めていいねした相手の記録)",
    chart: "line",
    unit: "人",
    labels: "week",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 9,
    category: C1,
    name: "恩人プレイヤー(自分の建築に初めていいねをくれた人)",
    chart: "hbar",
    unit: "人",
    source: SRC.inbound + "。初回判定は likedAt NULL の過去分が不完全",
    feasible: "partial",
  },
  {
    no: 10,
    category: C1,
    name: "一方通行の愛・片思い応援リスト",
    chart: "hbar",
    unit: "人",
    source: SRC.mutual,
    feasible: "yes",
  },
  {
    no: 11,
    category: C1,
    name: "いいねの温度差ランキング",
    chart: "hbar",
    unit: "差分",
    source: SRC.mutual,
    feasible: "yes",
  },
  {
    no: 12,
    category: C1,
    name: "共通の推し・似た好みのプレイヤー",
    chart: "hbar",
    unit: "一致",
    source: SRC.graph,
    feasible: "yes",
  },
  {
    no: 13,
    category: C1,
    name: "同日いいね仲間",
    chart: "hbar",
    unit: "回",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 14,
    category: C1,
    name: "いいねチェーン(数珠つなぎの交流)",
    chart: "hbar",
    unit: "連鎖",
    source: SRC.graph + "。時系列の連鎖は likedAt NULL で欠落する",
    feasible: "partial",
  },
  {
    no: 15,
    category: C1,
    name: "自分のファンがよく推す作者",
    chart: "hbar",
    unit: "いいね",
    source: SRC.graph,
    feasible: "yes",
  },
  {
    no: 16,
    category: C1,
    name: "新規ファン流入",
    chart: "line",
    unit: "人",
    labels: "week",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 17,
    category: C1,
    name: "復帰ファン",
    chart: "line",
    unit: "人",
    labels: "week",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 18,
    category: C1,
    name: "常連サポーター",
    chart: "hbar",
    unit: "週",
    source: SRC.inbound,
    feasible: "yes",
  },
  {
    no: 19,
    category: C1,
    name: "リピーター率",
    chart: "bar",
    unit: "%",
    max: 100,
    labels: "week",
    source: SRC.inbound,
    feasible: "yes",
  },
  {
    no: 20,
    category: C1,
    name: "新作最速サポーター",
    chart: "hbar",
    unit: "分",
    source: SRC.buildsTime,
    feasible: "partial",
  },
  {
    no: 21,
    category: C1,
    name: "久しぶりのいいね(最長ご無沙汰ペア)",
    chart: "hbar",
    unit: "日",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 22,
    category: C1,
    name: "いいね疲れチェック",
    chart: "line",
    unit: "いいね",
    labels: "week",
    source: SRC.time,
    feasible: "partial",
  },

  {
    no: 23,
    category: C2,
    name: "初速(作成→初いいね)",
    chart: "hbar",
    unit: "時間",
    source: SRC.buildsTime,
    feasible: "partial",
  },
  {
    no: 24,
    category: C2,
    name: "活動リズム(時間帯・曜日)",
    chart: "heat",
    unit: "いいね",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 25,
    category: C2,
    name: "月別ペース変化",
    chart: "line",
    unit: "いいね",
    labels: "month",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 26,
    category: C2,
    name: "いいね対象の築年数(掘り起こし傾向)",
    chart: "bar",
    unit: "件",
    source: SRC.buildsTime,
    feasible: "partial",
  },
  {
    no: 27,
    category: C2,
    name: "いいね継続日数(ストリーク)",
    chart: "line",
    unit: "日",
    labels: "week",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 28,
    category: C2,
    name: "受いいね連続週数",
    chart: "line",
    unit: "週",
    labels: "week",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 29,
    category: C2,
    name: "いいね空白期間",
    chart: "hbar",
    unit: "日",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 30,
    category: C2,
    name: "受いいね空白期間",
    chart: "hbar",
    unit: "日",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 31,
    category: C2,
    name: "深夜テンション・朝活いいね率",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 32,
    category: C2,
    name: "週末型・平日型判定",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 33,
    category: C2,
    name: "ロングテールいいね(公開30日後以降)",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.buildsTime,
    feasible: "partial",
  },
  {
    no: 34,
    category: C2,
    name: "月初・月末の偏り",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 35,
    category: C2,
    name: "いいね爆発日",
    chart: "hbar",
    unit: "いいね",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 36,
    category: C2,
    name: "指が滑った日",
    chart: "hbar",
    unit: "いいね",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 37,
    category: C2,
    name: "推し変履歴",
    chart: "line",
    unit: "作者",
    labels: "month",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 38,
    category: C2,
    name: "建築人生年表",
    chart: "area",
    unit: "建築",
    labels: "month",
    source: "Builds.createdAt を月別に GROUP BY",
    feasible: "yes",
  },
  {
    no: 39,
    category: C2,
    name: "隠居気味サイン",
    chart: "line",
    unit: "スコア",
    max: 100,
    labels: "week",
    source: SRC.subjective + "。入力値は " + SRC.time,
    feasible: "partial",
  },
  {
    no: 40,
    category: C2,
    name: "勢い復活サイン",
    chart: "line",
    unit: "スコア",
    max: 100,
    labels: "week",
    source: SRC.subjective + "。入力値は " + SRC.time,
    feasible: "partial",
  },
  {
    no: 41,
    category: C2,
    name: "スロースターター建築",
    chart: "hbar",
    unit: "日",
    source: SRC.buildsTime,
    feasible: "partial",
  },
  {
    no: 42,
    category: C2,
    name: "過去作愛され度",
    chart: "bar",
    unit: "いいね",
    source: SRC.buildsTime,
    feasible: "partial",
  },
  {
    no: 43,
    category: C2,
    name: "今年のふりかえり(年次レポート)",
    chart: "area",
    unit: "いいね",
    labels: "month",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 44,
    category: C2,
    name: "シーズン推移(四季別)",
    chart: "bar",
    unit: "いいね",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 45,
    category: C2,
    name: "最初のいいね記念日",
    chart: "bar",
    unit: "日",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 46,
    category: C2,
    name: "いいね数の自己ベスト更新履歴",
    chart: "line",
    unit: "最高",
    labels: "month",
    source: SRC.time,
    feasible: "partial",
  },

  {
    no: 47,
    category: C3,
    name: "ワールド別の反応",
    chart: "hbar",
    unit: "いいね",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 48,
    category: C3,
    name: "座標エリア別の人気",
    chart: "heat",
    unit: "いいね",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 49,
    category: C3,
    name: "特定エリアへの偏愛(同一チャンク)",
    chart: "hbar",
    unit: "いいね",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 50,
    category: C3,
    name: "未踏エリアマップ",
    chart: "heat",
    unit: "区画",
    source: SRC.missingVisit,
    feasible: "no",
  },
  {
    no: 51,
    category: C3,
    name: "ホームグラウンド",
    chart: "hbar",
    unit: "建築",
    source: "Builds.ownerUuid=自分を worldName / chunkX/Z で GROUP BY",
    feasible: "yes",
  },
  {
    no: 52,
    category: C3,
    name: "移動距離換算・いいね総移動距離",
    chart: "line",
    unit: "m",
    labels: "week",
    source: SRC.missingVisit,
    feasible: "no",
  },
  {
    no: 53,
    category: C3,
    name: "ワールド制覇率",
    chart: "bar",
    unit: "%",
    max: 100,
    source:
      "Builds に存在する worldName だけなら計算可能。全ワールド母数は設定が必要",
    feasible: "partial",
  },
  {
    no: 54,
    category: C3,
    name: "高度別反応(地下/地上/空中)",
    chart: "bar",
    unit: "いいね",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 55,
    category: C3,
    name: "スポーン距離別傾向(近郊vs辺境)",
    chart: "bar",
    unit: "いいね",
    source: "Builds.locX/Z はあるが各 world の spawn 座標は DB に無い",
    feasible: "partial",
  },
  {
    no: 56,
    category: C3,
    name: "辺境好き度",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: "locX/Z から原点距離は出せるが spawn 基準なら追加設定が必要",
    feasible: "partial",
  },
  {
    no: 57,
    category: C3,
    name: "平均標高",
    chart: "bar",
    unit: "Y",
    source: "Builds.locY を ownerUuid / liked build で AVG",
    feasible: "yes",
  },
  {
    no: 58,
    category: C3,
    name: "ネザー・ジ・エンド等特殊ワールド割合",
    chart: "bar",
    unit: "%",
    max: 100,
    source: "Builds.worldName の命名規則で分類。厳密な dimension は DB に無い",
    feasible: "partial",
  },
  {
    no: 59,
    category: C3,
    name: "ワールド移動傾向",
    chart: "line",
    unit: "回",
    labels: "week",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 60,
    category: C3,
    name: "ホームワールド依存度",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 61,
    category: C3,
    name: "チャンク内複数建築の総いいねランキング",
    chart: "hbar",
    unit: "いいね",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 62,
    category: C3,
    name: "推し巡礼マップ",
    chart: "heat",
    unit: "地点",
    source: "いいねした建築の座標は出せるが巡礼ルートや訪問実績は無い",
    feasible: "partial",
  },

  {
    no: 63,
    category: C4,
    name: "自分の建築ごとのいいね数ランキング",
    chart: "hbar",
    unit: "いいね",
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 64,
    category: C4,
    name: "直近伸びている建築",
    chart: "hbar",
    unit: "いいね",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 65,
    category: C4,
    name: "未いいね建築の掘り起こし",
    chart: "hbar",
    unit: "建築",
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 66,
    category: C4,
    name: "伸びしろがある建築",
    chart: "hbar",
    unit: "スコア",
    source: SRC.rank + "。スコア式は別途定義が必要",
    feasible: "partial",
  },
  {
    no: 67,
    category: C4,
    name: "一番乗り(First Discoverer)",
    chart: "hbar",
    unit: "回",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 68,
    category: C4,
    name: "未チェック(checked=false)の隠れた人気建築",
    chart: "hbar",
    unit: "いいね",
    source: SRC.rank + " + Builds.checked=false",
    feasible: "yes",
  },
  {
    no: 69,
    category: C4,
    name: "代表作候補(複合スコア)",
    chart: "hbar",
    unit: "スコア",
    max: 100,
    source: SRC.subjective + "。入力値は " + SRC.rank,
    feasible: "partial",
  },
  {
    no: 70,
    category: C4,
    name: "同期ランキング(参加時期が近い人との比較)",
    chart: "hbar",
    unit: "いいね",
    source: SRC.missingLogin + "。初建築 createdAt で代替するなら partial",
    feasible: "no",
  },
  {
    no: 71,
    category: C4,
    name: "いいね効率(建築数あたりの獲得数)",
    chart: "hbar",
    unit: "効率",
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 72,
    category: C4,
    name: "近傍比較(座標が近い建築主対決)",
    chart: "hbar",
    unit: "いいね",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 73,
    category: C4,
    name: "自分の建築平均いいね数とサーバー平均の比較",
    chart: "bar",
    unit: "平均",
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 74,
    category: C4,
    name: "押したいいね数と受け取ったいいね数の差分",
    chart: "bar",
    unit: "差分",
    labels: "week",
    source: SRC.mutual,
    feasible: "yes",
  },
  {
    no: 75,
    category: C4,
    name: "均等",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: SRC.rank + "。分散・ジニ係数などの定義が必要",
    feasible: "yes",
  },
  {
    no: 76,
    category: C4,
    name: "突出度",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: SRC.rank + "。最大値と中央値の比などで定義",
    feasible: "yes",
  },
  {
    no: 77,
    category: C4,
    name: "中央値いいね数",
    chart: "bar",
    unit: "いいね",
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 78,
    category: C4,
    name: "最新建築vs過去建築の反応比較",
    chart: "bar",
    unit: "いいね",
    source: SRC.buildsTime,
    feasible: "yes",
  },
  {
    no: 79,
    category: C4,
    name: "供養ルーム(いいねゼロの建築)",
    chart: "hbar",
    unit: "建築",
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 80,
    category: C4,
    name: "いいね集中度",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 81,
    category: C4,
    name: "沈黙の建築(最不遇建築ランキング、配慮要検討)",
    chart: "hbar",
    unit: "いいね",
    source: SRC.rank,
    feasible: "yes",
  },

  {
    no: 82,
    category: C5,
    name: "掲載効果(前後のいいね増減)",
    chart: "bar",
    unit: "差分",
    source: SRC.publicity,
    feasible: "yes",
  },
  {
    no: 83,
    category: C5,
    name: "紹介露出後24時間の反響",
    chart: "bar",
    unit: "いいね",
    source: SRC.publicity,
    feasible: "yes",
  },
  {
    no: 84,
    category: C5,
    name: "掲載回数ランキング",
    chart: "hbar",
    unit: "回",
    source: SRC.publicity,
    feasible: "yes",
  },
  {
    no: 85,
    category: C5,
    name: "掲載未経験だが人気の建築",
    chart: "hbar",
    unit: "いいね",
    source: SRC.publicity,
    feasible: "yes",
  },
  {
    no: 86,
    category: C5,
    name: "掲載されたのに反応が少なかった建築",
    chart: "hbar",
    unit: "いいね",
    source: SRC.publicity,
    feasible: "yes",
  },
  {
    no: 87,
    category: C5,
    name: "複数回掲載された建築の累計反響",
    chart: "hbar",
    unit: "いいね",
    source: SRC.publicity,
    feasible: "yes",
  },

  {
    no: 88,
    category: C6,
    name: "タイトル有無の反応差",
    chart: "bar",
    unit: "いいね",
    source: SRC.attr,
    feasible: "yes",
  },
  {
    no: 89,
    category: C6,
    name: "コメント有無の反応差",
    chart: "bar",
    unit: "いいね",
    source: SRC.attr,
    feasible: "yes",
  },
  {
    no: 90,
    category: C6,
    name: "タイトル文字数別反応",
    chart: "bar",
    unit: "いいね",
    source: SRC.attr,
    feasible: "yes",
  },
  {
    no: 91,
    category: C6,
    name: "コメント文字数別反応",
    chart: "bar",
    unit: "いいね",
    source: SRC.attr,
    feasible: "yes",
  },
  {
    no: 92,
    category: C6,
    name: "Discord連携あり",
    chart: "bar",
    unit: "いいね",
    source: SRC.attr + " + discordTextId IS NOT NULL",
    feasible: "yes",
  },
  {
    no: 93,
    category: C6,
    name: "なしの反応差",
    chart: "bar",
    unit: "差分",
    source: SRC.attr + " + discordTextId の有無比較",
    feasible: "yes",
  },
  {
    no: 94,
    category: C6,
    name: 'チェック済み建築へのいいね率("公式ウォッチャー度")',
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.attr + " + checked=true",
    feasible: "yes",
  },
  {
    no: 95,
    category: C6,
    name: "ご新規歓迎度",
    chart: "bar",
    unit: "%",
    max: 100,
    source:
      SRC.missingLogin + "。初建築 createdAt で初心者を近似するなら partial",
    feasible: "partial",
  },
  {
    no: 96,
    category: C6,
    name: "古参建築愛",
    chart: "bar",
    unit: "%",
    max: 100,
    source: "Builds.createdAt が古い建築への BuildLikes 割合で近似",
    feasible: "partial",
  },

  {
    no: 97,
    category: C7,
    name: "いいねコンプリートバッジ",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.achievement,
    feasible: "yes",
  },
  {
    no: 98,
    category: C7,
    name: "継続の証(ストリーク称号)",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 99,
    category: C7,
    name: "レアいいね発掘者実績",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time + "。低評価時点の判定は likedAt が必要",
    feasible: "partial",
  },
  {
    no: 100,
    category: C7,
    name: "いいねマラソン実績",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 101,
    category: C7,
    name: "初心者応援バッジ",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.missingLogin,
    feasible: "no",
  },
  {
    no: 102,
    category: C7,
    name: "発掘王バッジ",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.buildsTime,
    feasible: "partial",
  },
  {
    no: 103,
    category: C7,
    name: "流行追従バッジ",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time + "。流行の定義が必要",
    feasible: "partial",
  },
  {
    no: 104,
    category: C7,
    name: "逆張りバッジ",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.subjective + "。低人気判定は BuildLikes で近似",
    feasible: "partial",
  },
  {
    no: 105,
    category: C7,
    name: "世界旅行者バッジ",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 106,
    category: C7,
    name: "座標冒険家バッジ",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 107,
    category: C7,
    name: "皆勤サポーター",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 108,
    category: C7,
    name: "キリ番マイルストーン(累計100/500達成)",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.achievement,
    feasible: "yes",
  },
  {
    no: 109,
    category: C7,
    name: "鉱石ランクバッジ(鉄→ダイヤ)",
    chart: "bar",
    unit: "%",
    max: 100,
    source: SRC.achievement,
    feasible: "yes",
  },

  {
    no: 110,
    category: C8,
    name: "いいね占い",
    chart: "bar",
    unit: "運勢",
    max: 100,
    source: SRC.subjective + "。入力値は BuildLikes で作れる",
    feasible: "partial",
  },
  {
    no: 111,
    category: C8,
    name: "いいねDNA診断",
    chart: "bar",
    unit: "型",
    max: 100,
    source: SRC.subjective + "。分類軸の設計が必要",
    feasible: "partial",
  },
  {
    no: 112,
    category: C8,
    name: "もしいいねが通貨だったら換算",
    chart: "bar",
    unit: "コイン",
    source: "BuildLikes の累計件数に任意レートを掛ける",
    feasible: "yes",
  },

  {
    no: 113,
    category: C9,
    name: "いいねの偏り自己診断(多様性スコア)",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: SRC.graph,
    feasible: "yes",
  },
  {
    no: 114,
    category: C9,
    name: "初心を振り返る(最初にいいねした建築への再訪)",
    chart: "bar",
    unit: "日",
    source: SRC.time,
    feasible: "partial",
  },
  {
    no: 115,
    category: C9,
    name: "いいね行動履歴に基づくプレイスタイル診断",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: SRC.subjective,
    feasible: "partial",
  },
  {
    no: 116,
    category: C9,
    name: "推し活タイプ診断",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: SRC.subjective,
    feasible: "partial",
  },
  {
    no: 117,
    category: C9,
    name: "いいねの守備範囲バランス",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: SRC.graph,
    feasible: "yes",
  },
  {
    no: 118,
    category: C9,
    name: "自分の代表ワールド称号化",
    chart: "hbar",
    unit: "建築",
    source: SRC.space,
    feasible: "yes",
  },
  {
    no: 119,
    category: C9,
    name: "いいね基準の乖離(平均より甘い/厳しいか)",
    chart: "bar",
    unit: "差分",
    source: SRC.rank,
    feasible: "yes",
  },
  {
    no: 120,
    category: C9,
    name: "満遍なく型vs一点集中型診断",
    chart: "bar",
    unit: "スコア",
    max: 100,
    source: SRC.graph,
    feasible: "yes",
  },
];

var METRICS = METRIC_SPECS.map(makeMetric);
var METRICS_BY_ID = {};
METRICS.forEach(function (m) {
  METRICS_BY_ID[m.id] = m;
});
