[advancedban."1.21.10"]
id = 8_695
type = "spiget"

[axiom-paper-plugin."1.21.10"]
slug = "axiom-paper-plugin"
type = "modrinth"

[bkcommonlib."1.21.10"]
slug = "bkcommonlib"
type = "modrinth"

[bluemap."1.21.10"]
slug = "bluemap"
type = "modrinth"

[coreprotect."1.21.10"]
slug = "coreprotect"
type = "modrinth"

[crackshotguns."1.21.10"]
id = 48_301
type = "spiget"

[decentholograms."1.21.10"]
slug = "decentholograms"
type = "modrinth"

[discordsrv."1.21.10"]
slug = "discordsrv"
type = "modrinth"

[essentialsx."1.21.10"]
type = "url"
url = "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.22.0-dev+112-5baf239.jar"

[essentialsxchat."1.21.10"]
type = "url"
url = "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsXChat-2.22.0-dev+112-5baf239.jar"

[essentialsxspawn."1.21.10"]
type = "url"
url = "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsXSpawn-2.22.0-dev+112-5baf239.jar"

[fastasyncvoxelsniper."1.21.10"]
slug = "fastasyncvoxelsniper"
type = "modrinth"

[fastasyncworldedit."1.21.10"]
slug = "fastasyncworldedit"
type = "modrinth"

[floodgate."1.21.10"]
type = "url"
url = "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"

[floodgate-velocity.velocity]
type = "url"
url = "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity"

[geyser-velocity.velocity]
type = "url"
url = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity"

[gsit."1.21.10"]
slug = "gsit"
type = "modrinth"

[imageonmap."1.21.10"]
name = "ImageOnMap-5.1.1.jar"
owner = "okocraft"
repo = "ImageOnMap"
tag = "5.1.1"
type = "github"

[inventoryshop."1.21.10"]
id = 47_694
type = "spiget"

[joincommands."1.21.10"]
id = 51_758
type = "spiget"

[luckperms."1.21.10"]
slug = "luckperms"
type = "modrinth"

[lunachat."1.21.10"]
name = "LunaChat.jar"
owner = "f1w3"
repo = "LunaChat"
tag = "v3.0.16-fix"
type = "github"

[lwc."1.21.10"]
slug = "lwc"
type = "modrinth"

[minepacks."1.21.10"]
id = 19_286
type = "spiget"

[multiversecore."1.21.10"]
slug = "multiverse-core"
type = "modrinth"

[multiverseportals."1.21.10"]
slug = "multiverse-portals"
type = "modrinth"

[mycommand."1.21.10"]
id = 22_272
type = "spiget"

[nuvotifier."1.21.10"]
name = "nuvotifier.jar"
owner = "NuVotifier"
repo = "NuVotifier"
tag = "v2.7.3"
type = "github"

[openinv."1.21.10"]
name = "OpenInv.jar"
owner = "JiKoo"
repo = "OpenInv"
tag = "5.1.14"
type = "github"

[particlehats."1.21.10"]
id = 1_007
type = "spiget"

[placeholderapi."1.21.10"]
slug = "placeholderapi"
type = "modrinth"

[plugmanx."1.21.10"]
slug = "plugmanx"
type = "modrinth"

[protocollib."1.21.10"]
name = "ProtocolLib.jar"
owner = "dmulloy2"
repo = "ProtocolLib"
tag = "5.4.0"
type = "github"

[pvparena."1.21.10"]
id = 16_584
type = "spiget"

[signshop."1.21.10"]
id = 10_997
type = "spiget"

[simpleelevator."1.21.10"]
id = 44_462
type = "spiget"

[skinsrestorer."1.21.10"]
slug = "skinsrestorer"
type = "modrinth"

[skript."1.21.10"]
slug = "skript"
type = "modrinth"

[slotmachine."1.21.10"]
id = 22_023
type = "spiget"

[tab."1.21.10"]
slug = "tab-was-taken"
type = "modrinth"

[tntruneloaded."1.21.10"]
id = 53_359
type = "spiget"

[vault."1.21.10"]
id = 34_315
type = "spiget"

[veinminer."1.21.10"]
slug = "veinminer"
type = "modrinth"

[venturechat."1.21.10"]
id = 771
type = "spiget"

[viaversion."1.21.10"]
slug = "viaversion"
type = "modrinth"

[worldborder."1.21.10"]
name = "WorldBorder.jar"
owner = "PryPurity"
repo = "WorldBorder"
tag = "v2.1.5"
type = "github"

[worldeditsui."1.21.10"]
name = "WorldEditSUI-1.7.4.jar"
owner = "kennytv"
repo = "WorldEditSUI"
tag = "1.7.4"
type = "github"

[worldguard."1.21.10"]
slug = "worldguard"
type = "modrinth"

[zvoteparty."1.21.10"]
id = 95_603
type = "spiget"
