CREATE DATABASE IF NOT EXISTS co;
GRANT ALL PRIVILEGES ON co.* TO 'root'@'%' IDENTIFIED BY 'pigg1524';

CREATE DATABASE IF NOT EXISTS luckperms;
GRANT ALL PRIVILEGES ON luckperms.* TO 'root'@'%' IDENTIFIED BY 'pigg1524';

CREATE DATABASE IF NOT EXISTS backpack;
GRANT ALL PRIVILEGES ON backpack.* TO 'root'@'%' IDENTIFIED BY 'pigg1524';

CREATE DATABASE IF NOT EXISTS token;
GRANT ALL PRIVILEGES ON token.* TO 'root'@'%' IDENTIFIED BY 'pigg1524';

FLUSH PRIVILEGES;