services:
  purpur:
    image: itzg/minecraft-server:java21
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      TYPE: PURPUR
      VERSION: 1.20.1
      MEMORY: 2560M
      MAX_PLAYERS: 70
      MOTD: \u00A72\u00A7lおやさい鯖
      ICON: https://avatars.githubusercontent.com/u/70241145
      OVERRIDE_ICON: true
      USE_AIKAR_FLAGS: true
      TZ: Asia/Tokyo
      DIFFICULTY: 2
      PVP: false
      FORCE_GAMEMODE: true
      ENABLE_COMMAND_BLOCK: true
      SPAWN_ANIMALS: false
      SPAWN_MONSTERS: false
      SPAWN_NPCS: false
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 80
      SIMULATION_DISTANCE: 12
      VIEW_DISTANCE: 12
      LEVEL: main
      GENERATE_STRUCTURES: false
      SPAWN_PROTECTION: 0
      MAX_TICK_TIME: -1
      MAX_CHAINED_NEIGHBOR_UPDATES: 500000
      NETWORK_COMPRESSION_THRESHOLD: 512
      PAUSE_WHEN_EMPTY_SECONDS: 30
      PLAYER_IDLE_TIMEOUT: 6000
      ENABLE_ROLLING_LOGS: true
      LOG_TIMESTAMP: true
      # Plugins
      PLUGINS_FILE: /data/plugins.txt