x-minecraft-service: &minecraft-service
  image: itzg/minecraft-server:java24
  restart: unless-stopped
  environment:
    EULA: TRUE

services:
  minecraft-main-production:
    <<: *minecraft-service
    profiles:
      - production
    ports:
      - "25565:25565"
    volumes:
      - ./production/minecraft-main:/data

  minecraft-main-development:
    <<: *minecraft-service
    profiles:
      - development
    ports:
      - "25566:25566"
    volumes:
      - ./development/minecraft-main:/data
