[versions]
anvilgui = "1.10.8-SNAPSHOT"
kotlin = "2.2.20"
luckperms = "5.5"
# @pin
purpur-api = "1.21.5-R0.1-SNAPSHOT"
shadow = "9.1.0"
spotless = "7.2.1"
vault = "1.7"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.0"

[libraries]
anvilgui = { module = "net.wesjd:anvilgui", version.ref = "anvilgui" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
luckperms-api = { module = "net.luckperms:api", version.ref = "luckperms" }
purpur-api = { module = "org.purpurmc.purpur:purpur-api", version.ref = "purpur-api" }
shadow-plugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
