[versions]
kotlin = "2.2.0"
spotless = "7.0.4"
purpur-api = "1.21.5-R0.1-SNAPSHOT"
shadow = "9.0.0-beta17"
protobuf = "4.31.1"
connect = "0.7.3"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
shadow-plugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
purpur-api = { module = "org.purpurmc.purpur:purpur-api", version.ref = "purpur-api" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
connect-kotlin = { module = "com.connectrpc:connect-kotlin", version.ref = "connect" }
connect-kotlin-google-java-ext = { module = "com.connectrpc:connect-kotlin-google-java-ext", version.ref = "connect" }