# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  caddy = {
    pname = "caddy";
    version = "2.11.3";
    src = dockerTools.pullImage {
      imageName = "caddy";
      imageDigest = "sha256:ec18ee54aab3315c22e25f3b2babda73ff8007d39b13b3bd1bfffa2f0444c7d9";
      sha256 = "sha256-e7XCeWxwkjZKxLBOjc23j80pngi8jQZJ2kSfs7A9TaY=";
      finalImageTag = "2.11.3";
      os = "linux";
      arch = "amd64";
    };
  };
  mariadb = {
    pname = "mariadb";
    version = "10.4.28";
    src = dockerTools.pullImage {
      imageName = "mariadb";
      imageDigest = "sha256:d8369cb7020907b44ab0a7a73f855e41cbd5b6da16e01fbd8b8fe21200c7a854";
      sha256 = "sha256-pIEYzawoBIJI295R0ToQyueVVDGLfYItnn8mySwhvLs=";
      finalImageTag = "10.4.28";
      os = "linux";
      arch = "amd64";
    };
  };
  mc-backup = {
    pname = "mc-backup";
    version = "2026.6.2";
    src = dockerTools.pullImage {
      imageName = "itzg/mc-backup";
      imageDigest = "sha256:324971bd9b77867c5ee8ca510d071e63b96402995c0fb027b270e72f893140db";
      sha256 = "sha256-nd3L8u1LVXVjq6iPQqKrrtgPoCg8zI4DzvgP03uBjMk=";
      finalImageTag = "2026.6.2";
      os = "linux";
      arch = "amd64";
    };
  };
  mysql-backup = {
    pname = "mysql-backup";
    version = "1.4.0";
    src = dockerTools.pullImage {
      imageName = "databack/mysql-backup";
      imageDigest = "sha256:9a9a12dc942c370040ced1d43ab9f7d1162e9fde7f38b0f7749c3516d79a812c";
      sha256 = "sha256-6I4SlD+N7jzTDqH7hfu6C7Sh4ALaL6WpkWqTjrhoCK0=";
      finalImageTag = "1.4.0";
      os = "linux";
      arch = "amd64";
    };
  };
}
