# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alloy = {
    pname = "alloy";
    version = "v1.19.2";
    src = dockerTools.pullImage {
      imageName = "grafana/alloy";
      imageDigest = "sha256:b8ec653c44235fbe910879145dac3597d66b0aaecf60bcbbe82580767771a839";
      sha256 = "sha256-4H7bR6t4jSPuV4LNLBOwA8XCPMr2x281caZLbFnMJRI=";
      finalImageTag = "v1.19.2";
      os = "linux";
      arch = "amd64";
    };
  };
  caddy = {
    pname = "caddy";
    version = "2.11.3";
    src = dockerTools.pullImage {
      imageName = "caddy";
      imageDigest = "sha256:ec18ee54aab3315c22e25f3b2babda73ff8007d39b13b3bd1bfffa2f0444c7d9";
      sha256 = "sha256-e7XCeWxwkjZKxLBOjc23j80pngi8jQZJ2kSfs7A9TaY=";
      finalImageTag = "2.11.3";
      os = "linux";
      arch = "amd64";
    };
  };
  mariadb = {
    pname = "mariadb";
    version = "10.4.28";
    src = dockerTools.pullImage {
      imageName = "mariadb";
      imageDigest = "sha256:d8369cb7020907b44ab0a7a73f855e41cbd5b6da16e01fbd8b8fe21200c7a854";
      sha256 = "sha256-pIEYzawoBIJI295R0ToQyueVVDGLfYItnn8mySwhvLs=";
      finalImageTag = "10.4.28";
      os = "linux";
      arch = "amd64";
    };
  };
  mc-backup = {
    pname = "mc-backup";
    version = "2026.9.1";
    src = dockerTools.pullImage {
      imageName = "itzg/mc-backup";
      imageDigest = "sha256:0b6a10703723e8b2c03cf19e237aaebef91deeeafceb376968a659b32c11b66f";
      sha256 = "sha256-rDZr1d7hniLTfnaqt4svTIn9mGqlDjsittXswyi6Q+4=";
      finalImageTag = "2026.9.1";
      os = "linux";
      arch = "amd64";
    };
  };
  mc-monitor = {
    pname = "mc-monitor";
    version = "0.17.1";
    src = dockerTools.pullImage {
      imageName = "itzg/mc-monitor";
      imageDigest = "sha256:f0667f713856e953dc82c70a608b986b943b33f4b65a9dd55a8ede17fe48f34e";
      sha256 = "sha256-qtaPWj90wazHAY7JmysKRSKaZhD7OLV1PSP1w9dPjAc=";
      finalImageTag = "0.17.1";
      os = "linux";
      arch = "amd64";
    };
  };
  mysql-backup = {
    pname = "mysql-backup";
    version = "1.4.0";
    src = dockerTools.pullImage {
      imageName = "databack/mysql-backup";
      imageDigest = "sha256:9a9a12dc942c370040ced1d43ab9f7d1162e9fde7f38b0f7749c3516d79a812c";
      sha256 = "sha256-6I4SlD+N7jzTDqH7hfu6C7Sh4ALaL6WpkWqTjrhoCK0=";
      finalImageTag = "1.4.0";
      os = "linux";
      arch = "amd64";
    };
  };
}
