export const defaults = {
  CLOUDFLARE_ACCESS_KEY_ID: 'xxx',
  CLOUDFLARE_ACCOUNT_ID: 'xxx',
  CLOUDFLARE_API_TOKEN: 'unset_unset_unset_unset_unset_unset_unset',
  CLOUDFLARE_SECRET_ACCESS_KEY: 'xxx',
  DISCORD_TOKEN: 'xxx',
  DISCORD_WEBHOOK_URL: 'xxx',
  ENVIRONMENT: 'local',
  GITHUB_APP_ID: 'xxx',
  GITHUB_APP_INSTALLATION_ID: 'xxx',
  GITHUB_APP_PEM_FILE: 'xxx',
  INFISICAL_CLIENT_ID: 'xxx',
  INFISICAL_CLIENT_SECRET: 'xxx',
  MARIADB_PASSWORD: 'xxx',
  PUBLIC_IPV4: '192.0.2.0',
  R2_BUCKET_NAME: 'xxx',
  RESTIC_PASSWORD: 'xxx',
  RCON_PASSWORD: 'xxx',
  TF_API_TOKEN: 'xxx',
  TF_TOKEN_app_terraform_io: 'xxx',
  TLS_CA_PEM: 'xxx',
  TLS_CERT_PEM: 'xxx',
  TLS_KEY_PEM: 'xxx'
} as const
