export const secrets = [
  'CLOUDFLARE_ACCESS_KEY_ID',
  'CLOUDFLARE_ACCOUNT_ID',
  'CLOUDFLARE_API_TOKEN',
  'CLOUDFLARE_SECRET_ACCESS_KEY',
  'DISCORD_TOKEN',
  'DISCORD_WEBHOOK_URL',
  'DOTENV_PRIVATE_KEY',
  'DOTENV_PUBLIC_KEY',
  'ENVIRONMENT',
  'GITHUB_APP_ID',
  'GITHUB_APP_INSTALLATION_ID',
  'GITHUB_APP_PEM_FILE',
  'INFISICAL_CLIENT_ID',
  'INFISICAL_CLIENT_SECRET',
  'MARIADB_PASSWORD',
  'PUBLIC_IPV4',
  'R2_BUCKET_NAME',
  'RCON_PASSWORD',
  'RESTIC_PASSWORD',
  'TF_API_TOKEN',
  'TF_TOKEN_app_terraform_io',
  'TLS_CA_PEM',
  'TLS_CERT_PEM',
  'TLS_KEY_PEM'
] as const

export type Secrets = Readonly<Record<(typeof secrets)[number], string>>
