accepts-transfers=false
allow-flight=true
allow-nether=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=true
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=lifeworld
level-seed=
level-type=minecraft\:normal
log-ips=true
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=70
max-tick-time=60000
max-world-size=29999984
motd=\u00a7l \u00a7r                \u00a7b\u00a7lOyasai\u00a7f\u00a7lServer\u00a77 [v1.21.5]\u00a7r\n\u00a7l   \u00a7f         \u5efa\u7bc9\u52e2\u306f\u96c6\u5408\u3060\uff01\u5efa\u7bc9\uff01\u5efa\u7bc9\uff01\u5efa\u7bc9\uff01\uff01\uff01
network-compression-threshold=96
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-name=Unknown Server
server-port=25565
simulation-distance=10
snooper-enabled=true
spawn-animals=false
spawn-monsters=true
spawn-npcs=false
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=24
white-list=false