#!/usr/bin/env python3
"""Generate the CitiesSkyMine user guide from a command catalog."""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any


TOOL_DIR = Path(__file__).resolve().parent
PLUGIN_DIR = TOOL_DIR.parent
REPO_ROOT = PLUGIN_DIR.parent.parent
DEFAULT_CATALOG = TOOL_DIR / "csm_user_guide_catalog.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs/02_Docs/tools/citiesskymine-user-guide.md"
PLUGIN_YML = PLUGIN_DIR / "src/main/resources/plugin.yml"


def load_catalog(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        catalog = json.load(handle)
    validate_catalog(catalog)
    return catalog


def validate_catalog(catalog: dict[str, Any]) -> None:
    required_command_fields = {"name", "title", "canonical", "summary", "usage", "examples"}
    names: set[str] = set()
    shortcuts: set[str] = set()

    for command in catalog.get("commands", []):
        missing = required_command_fields - command.keys()
        if missing:
            raise ValueError(f"command is missing required fields: {sorted(missing)}")
        name = command["name"]
        if name in names:
            raise ValueError(f"duplicate command name: {name}")
        names.add(name)
        shortcut = command.get("shortcut")
        if shortcut:
            shortcut_name = shortcut.split()[0].removeprefix("/")
            if shortcut_name in shortcuts:
                raise ValueError(f"duplicate shortcut: {shortcut_name}")
            shortcuts.add(shortcut_name)

    registered = read_plugin_commands(PLUGIN_YML)
    missing_shortcuts = sorted(shortcut for shortcut in shortcuts if shortcut not in registered)
    if missing_shortcuts:
        raise ValueError(
            "catalog shortcut is not registered in plugin.yml: " + ", ".join(missing_shortcuts)
        )


def read_plugin_commands(path: Path) -> set[str]:
    commands: set[str] = set()
    in_commands = False
    command_pattern = re.compile(r'^\s{2}("?[^":]+"?):\s*$')

    for line in path.read_text(encoding="utf-8").splitlines():
        if line == "commands:":
            in_commands = True
            continue
        if in_commands and line and not line.startswith(" "):
            break
        if not in_commands:
            continue
        match = command_pattern.match(line)
        if match:
            commands.add(match.group(1).strip('"'))
    return commands


def render_code_block(lines: list[str]) -> list[str]:
    return ["```", *lines, "```"]


def render_command(command: dict[str, Any]) -> list[str]:
    title = command["title"]
    shortcut = command.get("shortcut")
    heading = f"## {title}"
    if shortcut:
        heading += f" ({shortcut.split()[0]})"

    lines = [
        heading,
        "",
        command["summary"],
        "",
        "### 使い方",
        "",
        *render_code_block(command["usage"]),
        "",
    ]

    examples = command.get("examples", [])
    if examples:
        lines.extend(["### 例", "", *render_code_block(examples), ""])

    details = command.get("details", [])
    if details:
        lines.extend(["### 補足", ""])
        lines.extend(f"- {detail}" for detail in details)
        lines.append("")

    return lines


def render_guide(catalog: dict[str, Any]) -> str:
    lines: list[str] = [
        f"# {catalog['title']}",
        "",
        "<!-- GENERATED BY plugins/CitiesSkyMine/tools/generate_user_guide.py. DO NOT EDIT DIRECTLY. -->",
        "",
        catalog["description"],
        "",
        "## 基本ルール",
        "",
    ]
    lines.extend(f"- {note}" for note in catalog.get("notes", []))
    lines.extend(["", "## コマンド一覧", "", "| コマンド | ショートカット | 説明 |", "|---|---|---|"])

    for command in catalog["commands"]:
        shortcut = command.get("shortcut", "")
        lines.append(f"| `{command['canonical']}` | `{shortcut}` | {command['summary']} |")

    lines.append("")
    for command in catalog["commands"]:
        lines.extend(render_command(command))

    compatibility_commands = catalog.get("compatibility_commands", [])
    if compatibility_commands:
        lines.extend(["## 互換コマンド", ""])
        for item in compatibility_commands:
            lines.append(f"- `{item['command']}`: {item['summary']}")
        lines.append("")

    tutorials = catalog.get("tutorials", [])
    if tutorials:
        lines.extend(["## チュートリアル", ""])
        for tutorial in tutorials:
            lines.extend([f"### {tutorial['title']}", ""])
            for index, step in enumerate(tutorial.get("steps", []), start=1):
                lines.append(f"{index}. {step}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def check_output(output_path: Path, rendered: str) -> int:
    existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
    if existing == rendered:
        return 0

    diff = difflib.unified_diff(
        existing.splitlines(),
        rendered.splitlines(),
        fromfile=str(output_path),
        tofile=f"{output_path} (generated)",
        lineterm="",
    )
    sys.stderr.write("\n".join(diff) + "\n")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args()

    catalog = load_catalog(args.catalog)
    rendered = render_guide(catalog)

    if args.check:
        return check_output(args.output, rendered)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
