name: setup-secrets
inputs:
  client-id:
    description: 'Infisical Client ID'
    required: true
  client-secret:
    description: 'Infisical Client Secret'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: infisical/secrets-action@v1.0.15
      with:
        project-slug: 'platform'
        env-slug: ${{ env.ENVIRONMENT }}
        client-id: ${{ inputs.client-id }}
        client-secret: ${{ inputs.client-secret }}
