#!/usr/bin/env node
import { cp, readdir, rm, writeFile } from 'node:fs/promises'
import { EOL } from 'node:os'
import { join, parse } from 'node:path'
import { directory } from '@oyasaiserver/lib/directory'
import { readFileContent, rf, writeFileSafe } from '@oyasaiserver/lib/fs'
import { createOnpremInfra } from '@oyasaiserver/onprem'
import { runtimeSecrets } from '@oyasaiserver/schema/runtime-secrets'
import { pascalCase } from 'change-case'
import { compile, type JSONSchema } from 'json-schema-to-typescript'
import { $, spinner, YAML } from 'zx'
import { readme } from '../assets/readme.ts'
import { environments } from '@oyasaiserver/lib/environments'

const out = 'gen'

await rm(out, rf)
await cp(join(import.meta.dirname, '../static'), out, rf)

await spinner('md', async () => {
  await writeFileSafe(`${out}/md/README.md`, readme)
})

await spinner('wrangler', async () => {
  const apps = await readdir('apps')
  await Promise.all(
    apps.map(async app => {
      await $`cd apps/${app} && wrangler types`
      const path = `apps/${app}/worker-configuration.d.ts`
      const content = await readFileContent(path)
      const patched = content
        .split(EOL)
        .filter(it => !it.startsWith('// Runtime types generated with workerd'))
        .join(EOL)
      await writeFileSafe(path, patched)
    })
  )
})

await spinner('json', async () => {
  const src = 'schema/json'
  const dirents = await readdir(src, {
    recursive: true,
    withFileTypes: true
  })
  const promises = dirents
    .filter(dirent => dirent.isFile())
    .map(async file => {
      const content = await readFileContent(join(file.parentPath, file.name))
      const inner = file.parentPath.substring(src.length)
      const schema = JSON.parse(content)
      const { name } = parse(file.name)
      await writeFileSafe(
        `${out}/json/ts/src/${inner}/${name}.ts`,
        `
          ${await compile(schema, name, {
            bannerComment: '',
            customName(schema: JSONSchema) {
              if (schema.title) {
                return pascalCase(name)
              }
            }
          })}
        `
      )
    })
  await Promise.all(promises)
})

await spinner('compose', async () => {
  for (const environment of Object.values(environments)) {
    const infra = createOnpremInfra(environment)
    await writeFileSafe(
      join(out, 'compose', `compose.${environment}.yaml`),
      YAML.stringify(infra)
    )
  }
})

await spinner('runtime-secrets', async () => {
  const keys = Object.keys(runtimeSecrets.def.innerType.def.shape)
  const runtimeSecretsKt = `
    /*
     * This file is auto-generated by codegen - do not edit manually.
    */
    package io.oyasai.lib
    
    import java.lang.System.getenv
    
    object RuntimeSecrets {
      ${keys.map(key => `val ${key.toUpperCase()} = secret("${key}")`).join(EOL)}
      
      private fun secret(key: String) = requireNotNull(getenv(key)) { 
        "Environment variable '$key' is not set." 
      }
    }
  `
  await writeFile(
    `${directory.root}/lib/kotlin/src/main/kotlin/io/oyasai/lib/RuntimeSecrets.kt`,
    runtimeSecretsKt
  )
})
