name: Setup Java

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: oracle
        java-version: "24"
    - uses: gradle/actions/setup-gradle@v4