name: Setup Java

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5.0.0
      with:
        cache: gradle
        distribution: temurin
        java-version-file: .tool-versions
    - uses: gradle/actions/setup-gradle@v4.4.3
      with:
        cache-overwrite-existing: true
