name: setup-java
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        cache: gradle
        distribution: temurin
        java-version-file: .tool-versions
    - uses: gradle/actions/setup-gradle@v5
      with:
        cache-overwrite-existing: true
