package com.github.oyasaiserver.vertex.util

import arrow.core.Either.Companion.catch
import arrow.core.firstOrNone
import com.github.oyasaiserver.vertex.Vertex.Companion.httpClient
import com.github.oyasaiserver.vertex.rest.Endpoint
import io.ktor.client.request.get
import io.ktor.client.statement.bodyAsText
import io.ktor.http.URLBuilder
import java.util.Locale
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonPrimitive

object Language {
    fun romanToHiragana(input: String): String {
        tailrec fun go(rem: String, acc: String): String =
            if (rem.isEmpty()) {
                acc
            } else {
                romajiMap.keys
                    .firstOrNone { rem.startsWith(it) }
                    .fold(
                        {
                            return go(rem.drop(1), acc + rem.first())
                        },
                        {
                            return go(rem.drop(it.length), acc + romajiMap.getValue(it))
                        },
                    )
            }
        return go(input.lowercase(Locale.JAPANESE), emptyString())
    }

    suspend fun transliterateWithGoogleApi(input: String) = catch {
        val jsonString =
            URLBuilder(Endpoint.GOOGLE_TRANSLITERATE.url)
                .apply {
                    parameters.append("langpair", "ja-Hira|ja")
                    parameters.append("text", input)
                }
                .build()
                .let { httpClient.get(it) }
                .bodyAsText()
        Json.parseToJsonElement(jsonString).jsonArray.joinToString(emptyString()) {
            it.jsonArray.last().jsonArray.first().jsonPrimitive.content
        }
    }

    private val romajiMap =
        sortedMapOf(
            compareByDescending { it },
            "a" to "あ",
            "i" to "い",
            "yi" to "い",
            "u" to "う",
            "wu" to "う",
            "whu" to "う",
            "e" to "え",
            "o" to "お",
            "wha" to "うぁ",
            "whi" to "うぃ",
            "wi" to "うぃ",
            "whe" to "うぇ",
            "we" to "うぇ",
            "who" to "うぉ",
            "wyi" to "ゐ",
            "wye" to "ゑ",
            "la" to "ぁ",
            "xa" to "ぁ",
            "li" to "ぃ",
            "xi" to "ぃ",
            "lyi" to "ぃ",
            "xyi" to "ぃ",
            "lu" to "ぅ",
            "xu" to "ぅ",
            "le" to "ぇ",
            "xe" to "ぇ",
            "lye" to "ぇ",
            "xye" to "ぇ",
            "lo" to "ぉ",
            "xo" to "ぉ",
            "ye" to "いぇ",
            "ka" to "か",
            "ca" to "か",
            "ki" to "き",
            "ku" to "く",
            "cu" to "く",
            "qu" to "く",
            "ke" to "け",
            "ko" to "こ",
            "co" to "こ",
            "kya" to "きゃ",
            "kyi" to "きぃ",
            "kyu" to "きゅ",
            "kye" to "きぇ",
            "kyo" to "きょ",
            "qya" to "くゃ",
            "qyu" to "くゅ",
            "qyo" to "くょ",
            "qwa" to "くぁ",
            "qa" to "くぁ",
            "kwa" to "くぁ",
            "qwi" to "くぃ",
            "qi" to "くぃ",
            "qyi" to "くぃ",
            "qwu" to "くぅ",
            "qwe" to "くぇ",
            "qe" to "くぇ",
            "qye" to "くぇ",
            "qwo" to "くぉ",
            "qo" to "くぉ",
            "kwo" to "くぉ",
            "ga" to "が",
            "gi" to "ぎ",
            "gu" to "ぐ",
            "ge" to "げ",
            "go" to "ご",
            "gya" to "ぎゃ",
            "gyi" to "ぎぃ",
            "gyu" to "ぎゅ",
            "gye" to "ぎぇ",
            "gyo" to "ぎょ",
            "gwa" to "ぐぁ",
            "gwi" to "ぐぃ",
            "gwu" to "ぐぅ",
            "gwe" to "ぐぇ",
            "gwo" to "ぐぉ",
            "lka" to "ヵ",
            "xka" to "ヵ",
            "lke" to "ヶ",
            "xke" to "ヶ",
            "sa" to "さ",
            "si" to "し",
            "ci" to "し",
            "shi" to "し",
            "su" to "す",
            "se" to "せ",
            "ce" to "せ",
            "so" to "そ",
            "sya" to "しゃ",
            "sha" to "しゃ",
            "syi" to "しぃ",
            "syu" to "しゅ",
            "shu" to "しゅ",
            "sye" to "しぇ",
            "she" to "しぇ",
            "syo" to "しょ",
            "sho" to "しょ",
            "swa" to "すぁ",
            "swi" to "すぃ",
            "swu" to "すぅ",
            "swe" to "すぇ",
            "swo" to "すぉ",
            "za" to "ざ",
            "zi" to "じ",
            "ji" to "じ",
            "zu" to "ず",
            "ze" to "ぜ",
            "zo" to "ぞ",
            "zya" to "じゃ",
            "ja" to "じゃ",
            "jya" to "じゃ",
            "zyi" to "じぃ",
            "jyi" to "じぃ",
            "zyu" to "じゅ",
            "ju" to "じゅ",
            "jyu" to "じゅ",
            "zye" to "じぇ",
            "je" to "じぇ",
            "jye" to "じぇ",
            "zyo" to "じょ",
            "jo" to "じょ",
            "jyo" to "じょ",
            "ta" to "た",
            "ti" to "ち",
            "chi" to "ち",
            "tu" to "つ",
            "tsu" to "つ",
            "te" to "て",
            "to" to "と",
            "tya" to "ちゃ",
            "cha" to "ちゃ",
            "cya" to "ちゃ",
            "tyi" to "ちぃ",
            "cyi" to "ちぃ",
            "tyu" to "ちゅ",
            "chu" to "ちゅ",
            "cyu" to "ちゅ",
            "tye" to "ちぇ",
            "che" to "ちぇ",
            "cye" to "ちぇ",
            "tyo" to "ちょ",
            "cho" to "ちょ",
            "cyo" to "ちょ",
            "tsa" to "つぁ",
            "tsi" to "つぃ",
            "tse" to "つぇ",
            "tso" to "つぉ",
            "tha" to "てゃ",
            "thi" to "てぃ",
            "thu" to "てゅ",
            "the" to "てぇ",
            "tho" to "てょ",
            "twa" to "とぁ",
            "twi" to "とぃ",
            "twu" to "とぅ",
            "twe" to "とぇ",
            "two" to "とぉ",
            "da" to "だ",
            "di" to "ぢ",
            "du" to "づ",
            "de" to "で",
            "do" to "ど",
            "dya" to "ぢゃ",
            "dyi" to "ぢぃ",
            "dyu" to "ぢゅ",
            "dye" to "ぢぇ",
            "dyo" to "ぢょ",
            "dha" to "でゃ",
            "dhi" to "でぃ",
            "dhu" to "でゅ",
            "dhe" to "でぇ",
            "dho" to "でょ",
            "dwa" to "どぁ",
            "dwi" to "どぃ",
            "dwu" to "どぅ",
            "dwe" to "どぇ",
            "dwo" to "どぉ",
            "ltu" to "っ",
            "xtu" to "っ",
            "ltsu" to "っ",
            "xtsu" to "っ",
            "na" to "な",
            "ni" to "に",
            "nu" to "ぬ",
            "ne" to "ね",
            "no" to "の",
            "nya" to "にゃ",
            "nyi" to "にぃ",
            "nyu" to "にゅ",
            "nye" to "にぇ",
            "nyo" to "にょ",
            "ha" to "は",
            "hi" to "ひ",
            "hu" to "ふ",
            "fu" to "ふ",
            "he" to "へ",
            "ho" to "ほ",
            "hya" to "ひゃ",
            "hyi" to "ひぃ",
            "hyu" to "ひゅ",
            "hye" to "ひぇ",
            "hyo" to "ひょ",
            "fwa" to "ふぁ",
            "fa" to "ふぁ",
            "fwi" to "ふぃ",
            "fi" to "ふぃ",
            "fyi" to "ふぃ",
            "fwu" to "ふぅ",
            "fwe" to "ふぇ",
            "fe" to "ふぇ",
            "fye" to "ふぇ",
            "fwo" to "ふぉ",
            "fo" to "ふぉ",
            "fya" to "ふゃ",
            "fyu" to "ふゅ",
            "fyo" to "ふょ",
            "ba" to "ば",
            "bi" to "び",
            "bu" to "ぶ",
            "be" to "べ",
            "bo" to "ぼ",
            "bya" to "びゃ",
            "byi" to "びぃ",
            "byu" to "びゅ",
            "bye" to "びぇ",
            "byo" to "びょ",
            "va" to "ヴぁ",
            "vi" to "ヴぃ",
            "vu" to "ヴ",
            "ve" to "ヴぇ",
            "vo" to "ヴぉ",
            "vya" to "ヴゃ",
            "vyi" to "ヴぃ",
            "vyu" to "ヴゅ",
            "vye" to "ヴぇ",
            "vyo" to "ヴょ",
            "pa" to "ぱ",
            "pi" to "ぴ",
            "pu" to "ぷ",
            "pe" to "ぺ",
            "po" to "ぽ",
            "pya" to "ぴゃ",
            "pyi" to "ぴぃ",
            "pyu" to "ぴゅ",
            "pye" to "ぴぇ",
            "pyo" to "ぴょ",
            "ma" to "ま",
            "mi" to "み",
            "mu" to "む",
            "me" to "め",
            "mo" to "も",
            "mya" to "みゃ",
            "myi" to "みぃ",
            "myu" to "みゅ",
            "mye" to "みぇ",
            "myo" to "みょ",
            "ya" to "や",
            "yu" to "ゆ",
            "yo" to "よ",
            "lya" to "ゃ",
            "xya" to "ゃ",
            "lyu" to "ゅ",
            "xyu" to "ゅ",
            "lyo" to "ょ",
            "xyo" to "ょ",
            "ra" to "ら",
            "ri" to "り",
            "ru" to "る",
            "re" to "れ",
            "ro" to "ろ",
            "rya" to "りゃ",
            "ryi" to "りぃ",
            "ryu" to "りゅ",
            "rye" to "りぇ",
            "ryo" to "りょ",
            "wa" to "わ",
            "wo" to "を",
            "lwa" to "ゎ",
            "xwa" to "ゎ",
            "n" to "ん",
            "nn" to "ん",
            "n'" to "ん",
            "xn" to "ん",
            "-" to "ー",
            "," to "、",
            "." to "。",
            "?" to "？",
            "!" to "！",
            "[" to "「",
            "]" to "」",
            "<" to "＜",
            ">" to "＞",
            "&" to "＆",
            "\"" to "”",
            "(" to "（",
            ")" to "）",
        )
}
