export const spiget = {
  ventureChat: 771,
  particleHats: 1007,
  protocolLib: 1997,
  advancedBan: 8695,
  signShop: 10997,
  myPet: 12725,
  nuvotifier: 13449,
  minepacks: 19286,
  slotMachine: 22023,
  myCommand: 22272,
  vault: 34315,
  simpleElevator: 44462,
  inventoryShop: 47694,
  crackshotGuns: 48301,
  joinCommands: 51758,
  tntrunReloaded: 53359,
  gsit: 62325,
  lwc: 69551,
  zVoteParty: 95603,
  skript: 114544
} as const

export const modrinth = {
  bkcommonlib: 'bkcommonlib:eDM0nv3D',
  coreprotect: 'coreprotect:anOhDobp',
  decentholograms: 'decentholograms:P9OaQjwQ',
  essentialsx: 'essentialsx:Oa9ZDzZq',
  essentialsxChatModule: 'essentialsx-chat-module:BdLUtz0O',
  essentialsxSpawn: 'essentialsx-spawn:RVbLg2Am',
  multiverseCore: 'multiverse-core',
  multiversePortals: 'multiverse-portals',
  placeholderapi: 'placeholderapi:vkuwyUC6',
  tabWasTaken: 'tab-was-taken',
  terra: 'terra:Ufl71nST',
  veinminer: 'veinminer',
  viaversion: 'viaversion',
  worldguard: 'worldguard:PO4MKx7e',
  fastasyncworldedit: 'fastasyncworldedit:o8Ytdhc5',
  luckperms: 'luckperms',
  plugmanx: 'plugmanx:bYRNAPF0',
  discordsrv: 'discordsrv',
  bluemap: 'bluemap'
} as const
