export const spiget = {
  ventureChat: 771,
  particleHats: 1007,
  protocolLib: 1997,
  advancedBan: 8695,
  signShop: 10997,
  myPet: 12725,
  nuvotifier: 13449,
  minepacks: 19286,
  slotMachine: 22023,
  myCommand: 22272,
  vault: 34315,
  simpleElevator: 44462,
  inventoryShop: 47694,
  crackshotGuns: 48301,
  joinCommands: 51758,
  tntrunReloaded: 53359,
  gsit: 62325,
  lwc: 69551,
  zVoteParty: 95603,
  skript: 114544
} as const

export const modrinth = {
  bkcommonlib: 'bkcommonlib',
  coreprotect: 'coreprotect',
  decentholograms: 'decentholograms',
  essentialsx: 'essentialsx',
  essentialsxChatModule: 'essentialsx-chat-module',
  essentialsxSpawn: 'essentialsx-spawn',
  fastasyncworldedit: 'fastasyncworldedit',
  fastasyncvoxelsniper: 'fastasyncvoxelsniper:IT60kfto',
  multiverseCore: 'multiverse-core',
  multiversePortals: 'multiverse-portals',
  placeholderapi: 'placeholderapi',
  tabWasTaken: 'tab-was-taken',
  terra: 'terra',
  veinminer: 'veinminer',
  viaversion: 'viaversion',
  worldguard: 'worldguard',
  luckperms: 'luckperms',
  plugmanx: 'plugmanx',
  discordsrv: 'discordsrv',
  bluemap: 'bluemap'
} as const
