x-minecraft-service: &minecraft-service
  image: itzg/minecraft-server:java24
  restart: always
  tty: true
  stdin_open: true
  environment:
    EULA: TRUE
    TYPE: PURPUR
    VERSION: 1.21.5

services:
  minecraft-main-production:
    <<: *minecraft-service
    profiles:
      - production
    ports:
      - "25565:25565"
    volumes:
      - ./production/minecraft-main:/data

  minecraft-main-development:
    <<: *minecraft-service
    profiles:
      - development
    ports:
      - "25566:25565"
    volumes:
      - ./development/minecraft-main:/data

  minecraft-main-local:
    <<: *minecraft-service
    profiles:
      - local
    ports:
      - "25565:25565"
    volumes:
      - ./local/minecraft-main:/data
