{
 "title": "Oyasai Minecraft",
 "tags": [ "minecraft" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Main Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_status_healthy{host=\"oyasai-minecraft-main\"}"
    }
   ]
  },
  {
   "title": "Lobby Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_status_healthy{host=\"oyasai-minecraft-lobby\"}"
    }
   ]
  },
  {
   "title": "Main Players Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_status_players_online{host=\"oyasai-minecraft-main\"}"
    }
   ]
  },
  {
   "title": "Lobby Players Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_status_players_online{host=\"oyasai-minecraft-lobby\"}"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_status_players_online{host=\"oyasai-minecraft-main\"}",
     "legendFormat": "Main"
    },
    {
     "expr": "mc_status_players_online{host=\"oyasai-minecraft-lobby\"}",
     "legendFormat": "Lobby"
    }
   ]
  },
  {
   "title": "Server Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mc_status_response_time_seconds{host=\"oyasai-minecraft-main\"}",
     "legendFormat": "Main"
    },
    {
     "expr": "mc_status_response_time_seconds{host=\"oyasai-minecraft-lobby\"}",
     "legendFormat": "Lobby"
    }
   ]
  },
  {
   "title": "Minecraft Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{container=~\"oyasai-minecraft.*\"}"
    }
   ]
  }
 ]
}