
    /**
     * This file is auto-generated by @platform/env.
     * DO NOT EDIT THIS FILE MANUALLY.
     */
    export interface EnvType {
      CLOUDFLARE_API_TOKEN: string;DOTENV_PUBLIC_KEY: string;TF_API_TOKEN: string
    }
  