/**
 * This file is auto-generated by @platform/env at 2025-05-24T09:23:09.263Z.
 */
export type EnvType = Readonly<{
  ENVIRONMENT: 'development' | 'local' | 'production'
  CLOUDFLARE_API_TOKEN: string
  DOTENV_PUBLIC_KEY: string
  TF_API_TOKEN: string
  TF_TOKEN_app_terraform_io: string
}>
