/**
 * This file is auto-generated by @platform/env.
 * DO NOT EDIT THIS FILE MANUALLY.
 */
export type EnvType = Readonly<{
  ENVIRONMENT: 'development' | 'local' | 'production'
  CLOUDFLARE_API_TOKEN: string
  DOTENV_PUBLIC_KEY: string
  TF_TOKEN_app_terraform_io: string
}>
