services:
  mariadb:
    image: mariadb:10.4.28
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: pigg1524
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
  minecraft-main:
    depends_on:
      - mariadb
    image: itzg/minecraft-server:java24-graalvm
    ports:
      - 25566:25565/tcp
      - 19133:19132/udp
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: true
      TYPE: PURPUR
      VERSION: 1.21.5
      USE_MEOWICE_FLAGS: true
      ENABLE_ROLLING_LOGS: true
      LOG_TIMESTAMP: true
      MEMORY: 16G
      PLUGINS: https://github.com/EssentialsX/Essentials/releases/download/2.21.1/EssentialsX-2.21.1.jar,https://github.com/EssentialsX/Essentials/releases/download/2.21.1/EssentialsXChat-2.21.1.jar,https://github.com/EssentialsX/Essentials/releases/download/2.21.1/EssentialsXSpawn-2.21.1.jar,https://github.com/Test-Account666/PlugManX/releases/download/2.4.1/PlugManX-2.4.1.jar,https://github.com/dmulloy2/ProtocolLib/releases/download/5.4.0/ProtocolLib.jar,https://github.com/NicoNekoDev/VoidGen/releases/download/2.2.9/VoidGen-2.2.9.jar,https://github.com/DiscordSRV/DiscordSRV/releases/download/v1.29.0/DiscordSRV-Build-1.29.0.jar,https://github.com/NEZNAMY/TAB/releases/download/5.2.5/TAB.v5.2.5.jar,https://github.com/Multiverse/Multiverse-Core/releases/download/5.1.2/multiverse-core-5.1.2.jar,https://github.com/Multiverse/Multiverse-Portals/releases/download/5.1.0/multiverse-portals-5.1.0.jar,https://github.com/f1w3/LunaChat/releases/download/v3.0.16-fix/LunaChat.jar,https://github.com/XZot1K/DisplayShops/releases/download/2.0/DisplayShops_2.0.1.jar,https://github.com/DevLeoko/AdvancedBan/releases/download/v2.3.0/AdvancedBan-Bundle-2.3.0-RELEASE.jar,https://github.com/NuVotifier/NuVotifier/releases/download/v2.7.3/nuvotifier.jar,https://cdn.modrinth.com/data/FIlZB9L0/versions/GXo6GGY8/Terra-bukkit-6.6.3-BETA%2Bcc5258ce7-shaded.jar,https://ci.athion.net/job/FastAsyncWorldEdit/1160/artifact/artifacts/FastAsyncWorldEdit-Paper-2.13.2-SNAPSHOT-1160.jar,https://dev.bukkit.org/projects/worldguard/files/6643567/download,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.luckperms.net/1594/bukkit/loader/LuckPerms-Bukkit-5.5.9.jar,https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.4.2/PAPER/ViaVersion-5.4.2.jar
      ICON: https://avatars.githubusercontent.com/oyasaiserver
      REMOVE_OLD_MODS: true
      REMOVE_OLD_MODS_EXCLUDE: Arceon-0.5.2.jar,BKCommonLib-1.21.5-v1-1864.jar,ChestCommands.jar,CrackShot.jar,DecentHolograms-2.9.1.jar,Elevator.jar,GSit-2.3.3.jar,ImageOnMap-5.1.1.jar,JoinCommands-3.1.0.120.jar,Minepacks.jar,MyCommand.jar,MyPet-3.12-SNAPSHOT-B1780.jar,MyPetDownloader-v1.2.jar,OpenInv.jar,OyasaiUtilities-0.1.0-all.jar,PaintTools-1.6.2.jar,ParticleHats.jar,PlaceholderAPI-2.11.6.jar,SQLiteLib.jar,Shop.jar,SignShop-4.0.0.jar,Skript-2.9.1.jar,SocialLikes3-0.5.3-all.jar,SrainEventPack-0.2.3.jar,TNTRun_reloaded-9.29.jar,TPswitch-0.1.7.jar,TokenManager-3.2.8-re1.jar,Vault.jar,VentureChat.jar,WorldBorder.jar,WorldEditSUI-1.7.4.jar,WorldJoinCommand.jar,ezEdits-0.13.0.jar,shobos-someitems-0.1.2.jar,slotmachine-6.8.5.jar,veinminer-bukkit-2.2.4.jar,voxelsniper-8.14.0-spigot.jar
    volumes:
      - ./minecraft-main:/data
    env_file: .env
volumes: {}
