services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: UTC
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command:
      - sh
      - -c
      - |-
        cat <<'EOF' > /etc/caddy/development.Caddyfile
        dev.oyasai.io {
          redir http://wiki.dev.oyasai.io{uri} permanent
        }
        EOF
        caddy run --config /etc/caddy/development.Caddyfile --adapter caddyfile
  minecraft-main:
    image: itzg/minecraft-server:java24
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-main:/data
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: 'TRUE'
      TYPE: PURPUR
      VERSION: 1.21.5
    env_file: .env
volumes:
  caddy_data: {}
  caddy_config: {}
