services:
  portical:
    image: danielbodart/portical:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    command: /opt/portical/run poll
  mariadb:
    image: mariadb:10.4.28
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: pigg1524
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
  minecraft-main:
    depends_on:
      - mariadb
      - portical
    image: itzg/minecraft-server:java24
    ports:
      - 25566:25565/tcp
      - 19133:19132/udp
    labels:
      - portical.upnp.forward=25566/tcp,19133/udp
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: true
      TYPE: PURPUR
      VERSION: 1.21.5
      USE_MEOWICE_FLAGS: true
      ENABLE_ROLLING_LOGS: true
      LOG_TIMESTAMP: true
      MEMORY: 12G
      ICON: https://avatars.githubusercontent.com/oyasaiserver
    volumes:
      - ./minecraft-main:/data
    env_file: .env
