services:
  mariadb:
    image: mariadb:10.4.28
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: pigg1524
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
  minecraft-main:
    depends_on:
      - mariadb
    image: itzg/minecraft-server:java24
    ports:
      - 25565:25565/tcp
      - 19132:19132/udp
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: true
      TYPE: PURPUR
      VERSION: 1.21.5
      USE_MEOWICE_FLAGS: false
      ENABLE_ROLLING_LOGS: true
      LOG_TIMESTAMP: true
      MEMORY: 3G
      PLUGINS: https://github.com/EssentialsX/Essentials/releases/download/2.21.1/EssentialsX-2.21.1.jar,https://github.com/EssentialsX/Essentials/releases/download/2.21.1/EssentialsXChat-2.21.1.jar,https://github.com/EssentialsX/Essentials/releases/download/2.21.1/EssentialsXSpawn-2.21.1.jar,https://download.luckperms.net/1594/bukkit/loader/LuckPerms-Bukkit-5.5.9.jar,https://github.com/Test-Account666/PlugManX/releases/download/2.4.1/PlugManX-2.4.1.jar,https://ci.dmulloy2.net/job/ProtocolLib/753/artifact/build/libs/ProtocolLib.jar,https://ci.athion.net/job/FastAsyncWorldEdit/1131/artifact/artifacts/FastAsyncWorldEdit-Paper-2.13.1-SNAPSHOT-1131.jar,https://dev.bukkit.org/projects/worldguard/files/6643567/download,https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.4.2/PAPER/ViaVersion-5.4.2.jar,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://github.com/DiscordSRV/DiscordSRV/releases/download/v1.29.0/DiscordSRV-Build-1.29.0.jar,https://github.com/NEZNAMY/TAB/releases/download/5.2.5/TAB.v5.2.5.jar,https://github.com/Multiverse/Multiverse-Core/releases/download/5.1.2/multiverse-core-5.1.2.jar,https://github.com/Multiverse/Multiverse-Portals/releases/download/5.1.0/multiverse-portals-5.1.0.jar,https://github.com/f1w3/LunaChat/releases/download/v3.0.16-fix/LunaChat.jar,https://github.com/XZot1K/DisplayShops/releases/download/2.0/DisplayShops_2.0.1.jar,https://cdn.modrinth.com/data/FIlZB9L0/versions/GXo6GGY8/Terra-bukkit-6.6.3-BETA%2Bcc5258ce7-shaded.jar,https://github.com/NicoNekoDev/VoidGen/releases/download/2.2.9/VoidGen-2.2.9.jar
      ICON: https://avatars.githubusercontent.com/oyasaiserver
    volumes:
      - ./minecraft-main:/data
    env_file: .env
