name: CD

on:
  push:
    branches:
      - main

jobs:
  cdktf:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: hashicorp/setup-terraform@v3
      - name: Deploy CDKTF stack
        run: npm run deploy:ci -w infra/cdktf
        env:
          DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
