name: CD
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: "⚠️ Manual deploy ⚠️"
        required: true
        default: production
        type: choice
        options:
          - production
          - development
jobs:
  envs:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.environment.outputs.ENVIRONMENT }}
    steps:
      - id: environment
        run: |
          ENVIRONMENT="development"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENVIRONMENT="${{ github.event.inputs.environment }}"
          fi
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_OUTPUT"
  cdktf:
    needs:
      - envs
    runs-on: ubuntu-latest
    environment: ${{ needs.envs.outputs.environment }}
    env:
      ENVIRONMENT: ${{ needs.envs.outputs.environment }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
      - uses: DeterminateSystems/magic-nix-cache-action@c2f46a0afa5f95fd4c184a533afd280c68cf63ff
      - uses: nicknovitski/nix-develop@5da6ac475f1ffbcf54ee562fa3056646e146be95
      - name: Build plugins
        run: |
          ./gradlew build --parallel
      - name: Download plugins
        run: |
          npm ci
          npm run download-plugins
        working-directory: packages/minecraft-main
      - uses: ./.github/actions/setup-secrets
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
      - name: Deploy
        run: |
          npm ci
          npm run build --workspaces --if-present
          npm run deploy -w packages/cdktf
  actions-timeline:
    needs:
      - envs
      - cdktf
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca
