name: CI

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - run: ./gradlew spotlessCheck --parallel
      - uses: ./.github/actions/setup-node
      - run: npm run check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npm run build

  codegen-no-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npm run codegen
      - run: npm run check
      - run: git diff --exit-code

  build-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - run: ./gradlew build --parallel

  actions-timeline:
    runs-on: ubuntu-latest
    needs:
      - format
      - typecheck
      - codegen-no-drift
      - build-plugins
    steps:
      - uses: Kesin11/actions-timeline@v2