name: CI
on:
  pull_request:
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: ./.github/actions/setup-node
      - run: |
          npm run lint
          npm run format
          test -z "$(git status --porcelain)"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: ./.github/actions/setup-node
      - run: |
          npm run build --workspaces --if-present
  build-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: ./.github/actions/setup-java
      - run: |
          ./gradlew build --parallel
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: ./.github/actions/setup-node
      - run: |
          npm run test --workspaces --if-present
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-terraform
      - run: |
          npm run test:integration --workspaces --if-present
  actions-timeline:
    needs:
      - nocommit
      - check
      - build
      - build-plugins
      - test-unit
      - test-integration
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
