name: Deploy Platform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write

jobs:
  push-to-ghcr:
    uses: ./.github/workflows/push-to-ghcr.yaml
    secrets: inherit

  infra:
    secrets: inherit
    uses: ./.github/workflows/modify-platform-stack.yaml
    with:
      environment: ${{ inputs.environment }}
      stack: infra
      operation: deploy

  services:
    needs:
      - push-to-ghcr
      - infra
    secrets: inherit
    uses: ./.github/workflows/modify-platform-stack.yaml
    with:
      environment: ${{ inputs.environment }}
      stack: services
      operation: deploy
