name: Deploy Platform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write

jobs:
  infra:
    secrets: inherit
    uses: ./.github/workflows/modify-platform-stack.yaml
    with:
      environment: ${{ inputs.environment }}
      stack: infra
      operation: deploy

  services:
    needs:
      - infra
    secrets: inherit
    uses: ./.github/workflows/modify-platform-stack.yaml
    with:
      environment: ${{ inputs.environment }}
      stack: services
      operation: deploy
