name: Deploy

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  # Minimal deploy. We'd probably want "full deploy", i.e. spin up production-
  # clone infrastructure using tf.
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment:
      name: "pr-${{ github.event.pull_request.number }}"
    # Keeping it low for now. But it's free so we can absolutely set it higher.
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          key: "nix-eval-cache-${{ runner.os }}-${{ runner.arch }}"
          path: "~/.cache/nix"
      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe
        with:
          extra_nix_config: |
            extra-substituters = ${{ vars.NIX_CACHE_SUBSTITUTER }}
            extra-trusted-public-keys = ${{ vars.NIX_CACHE_PUBLIC_KEY }}
      - name: Configure Cloudflare R2 credentials
        run: |
          aws configure set aws_access_key_id "${{ vars.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - uses: nix-ocaml/nix-s3-action@84d7b6415d8603e815741fe77f0aaffa22736d4b
        with:
          endpoint: ${{ vars.NIX_CACHE_SUBSTITUTER }}
          signingKey: "${{ secrets.NIX_CACHE_SIGNING_KEY }}"
      - run: nix profile add nixpkgs#bore-cli
      - name: Compute tunnel config
        id: tunnel-config
        run: |
          PORT=$((1024 + ${{ github.event.pull_request.number }} % 64512))
          ADDR="bore.pub"

          echo "port=$PORT" >> "$GITHUB_OUTPUT"
          echo "addr=$ADDR" >> "$GITHUB_OUTPUT"
      - uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Deployed at:**
            ```
            ${{ steps.tunnel-config.outputs.addr }}:${{ steps.tunnel-config.outputs.port }}
            ```
            **[Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.check_run_id }})**
      - name: Start server and tunnel
        run: |
          bore local 25565 \
            --to ${{ steps.tunnel-config.outputs.addr }} \
            --port ${{ steps.tunnel-config.outputs.port }} &
          nix run .#oyasai-minecraft-minimal
