name: Modify platform stack

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      environment:
        type: string
        required: true
      operation:
        type: string
        required: true
      cancel-in-progress:
        type: boolean
        required: false
        default: false
      start-proxy:
        type: boolean
        required: false
        default: false

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.stack }}
      cancel-in-progress: ${{ inputs.cancel-in-progress }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: packages/oyasai-cdktf
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          key: "nix-eval-cache-${{ runner.os }}-${{ runner.arch }}"
          path: "~/.cache/nix"
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f
        with:
          extra_nix_config: |
            extra-substituters = ${{ vars.NIX_CACHE_SUBSTITUTER }}
            extra-trusted-public-keys = ${{ vars.NIX_CACHE_PUBLIC_KEY }}
      - name: Configure Cloudflare R2 credentials
        run: |
          sudo -i aws configure set aws_access_key_id "${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}"
          sudo -i aws configure set aws_secret_access_key "${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}"
      - name: Setup Nix S3 cache
        uses: ./packages/nix-copy-action
        with:
          endpoint: ${{ vars.NIX_CACHE_SUBSTITUTER }}
          signing-key: "${{ secrets.NIX_CACHE_SIGNING_KEY }}"
      - name: Compute docker image names
        run: |
          nix build .#all-docker-tags.json
          echo "OYASAI_IMAGE_ID=$(<result tee /dev/stderr)" >> "$GITHUB_ENV"
      - uses: ./packages/oyasai-secrets-action
        with:
          env-slug: common
          project-slug: platform
          identity-id: "c3685c4e-acbd-4668-aca0-1920d1e0c83d"
      - name: Create TF Workspace
        if: inputs.operation == 'deploy'
        run: |
          nix run .#oyasai-infra -- \
            terraform_io::create_workspace \
            ${{ inputs.stack }}
      - name: ${{ inputs.operation }}
        run: |
          nix run .#oyasai-cdktf -- \
            ${{ inputs.operation }} \
            ${{ inputs.stack }} \
            --ignore-missing-stack-dependencies \
            --auto-approve
      - name: Delete TF Workspace
        if: inputs.operation == 'destroy'
        run: |
          nix run .#oyasai-infra -- \
            terraform_io::delete_workspace \
            ${{ inputs.stack }}
      - name: Start Proxy
        if: inputs.start-proxy
        # It's free, feel free to increase
        timeout-minutes: 20
        run: |
          nix run .#bore-cli -- local 25565 \
            --to bore.pub
