name: PR
on:
  pull_request:
jobs:
  merging-into-master:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: |
          [[ "$GITHUB_BASE_REF" == master ]]
  pr-title:
    runs-on: ubuntu-slim
    steps:
      - run: |
          <<<"$TITLE" grep '^\(build\|chore\|ci\|docs\|feat\|fix\|perf\|p\?refactor\|revert\|style\|test\)\(([a-zA-Z0-9_-]\+)\)\?!\?: '
        env:
          TITLE: "${{ github.event.pull_request.title }}"
