name: PR
on:
  pull_request:
jobs:
  merging-into-master:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - run: |
          [[ "$GITHUB_BASE_REF" == master ]]
  pr-title:
    runs-on: ubuntu-slim
    steps:
      - run: |
          <<<"$TITLE" grep '^\(build\|chore\|ci\|docs\|feat\|fix\|perf\|p\?refactor\|revert\|style\|test\)\(([a-zA-Z0-9_-]\+)\)\?!\?: '
        env:
          TITLE: "${{ github.event.pull_request.title }}"
