name: PR
on:
  pull_request:
jobs:
  merging-into-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - run: |
          [[ "$GITHUB_BASE_REF" == master ]]
  pr-title-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
