name: Push to GHCR
on:
  workflow_call:
jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          key: "nix-eval-cache-${{ runner.os }}-${{ runner.arch }}"
          path: "~/.cache/nix"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe
      - name: Configure Cloudflare R2 credentials
        run: |
          sudo -i aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          sudo -i aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Setup Nix S3 cache
        uses: ./packages/nix-copy-action
        with:
          endpoint: ${{ vars.NIX_CACHE_SUBSTITUTER }}
          signing-key: "${{ secrets.NIX_CACHE_SIGNING_KEY }}"
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: nix run .#oyasai-push-nix-images
