name: Push to GHCR
on:
  workflow_call:
jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          key: "nix-eval-cache-${{ runner.os }}-${{ runner.arch }}"
          path: "~/.cache/nix"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
      - uses: ./packages/oyasai-secrets-action
        with:
          env-slug: common
          project-slug: platform
          identity-id: "c3685c4e-acbd-4668-aca0-1920d1e0c83d"
          secrets: |
            CLOUDFLARE_ACCESS_KEY_ID
            CLOUDFLARE_SECRET_ACCESS_KEY
            NIX_CACHE_SIGNING_KEY
      - name: Configure Cloudflare R2 credentials
        run: |
          sudo -i aws configure set aws_access_key_id "$CLOUDFLARE_ACCESS_KEY_ID"
          sudo -i aws configure set aws_secret_access_key "$CLOUDFLARE_SECRET_ACCESS_KEY"
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: nix run .#oyasai-push-nix-images
      - run: nix run .#nix-copy-to-s3
        if: always()
        env:
          NIX_CACHE_SUBSTITUTER: ${{ vars.NIX_CACHE_SUBSTITUTER }}
